CREATE TABLE IF NOT EXISTS password_table (
	username VARCHAR(50) NOT NULL,
	password VARCHAR(300) NOT NULL,
	user_type BOOL NOT NULL,
	PRIMARY KEY(username)
);
	
CREATE TABLE IF NOT EXISTS admin_table (
	id INT(5) NOT NULL AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(300) NOT NULL,
	user_type BOOL NOT NULL,
	PRIMARY KEY(id)
);
	
CREATE TABLE IF NOT EXISTS user_table (
	id INT(5) AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	surname VARCHAR(50) NOT NULL,
	gender VARCHAR(1),
	indexNumber VARCHAR(10) NOT NULL,
	emailAddress VARCHAR(100) NOT NULL,
	telephone VARCHAR(20) NOT NULL,
	gradedPoint DECIMAL(5, 4) NOT NULL,
	aboutMe VARCHAR(500) NOT NULL,
	vacancy_A VARCHAR(20),
	status_A BOOL,
	vacancy_B VARCHAR(20),
	status_B BOOL,
	vacancy_C VARCHAR(20),
	status_C BOOL,
	appeal VARCHAR(20),
	appealStatus BOOL,
	awardedVacancy INT(5),
	awarded BOOL,
	ARDUINO BOOL,
	FPGA BOOL,
	ROBOTICS BOOL,
	WIFI BOOL,
	ANTENNAS BOOL,
	NETWORKING BOOL,
	PROCESSORDESIGN BOOL,
	IMAGEPROCESSING BOOL,
	PROGRAMMING BOOL,
	AUTOMATION BOOL,
	BIOMEDICAL BOOL,
	BIOMECHANICS BOOL,
	TELECOM BOOL,
	SEMICONDUCTORS BOOL,
	CIRCUITS BOOL,
	IOT BOOL,
	AI BOOL,
	SIGNALPROCESSING BOOL,
	UNIQUE (indexNumber),
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS company_table (
	id INT(5) AUTO_INCREMENT,
	loginID VARCHAR(100) NOT NULL,
	company VARCHAR(50) NOT NULL,
	address VARCHAR(150) NOT NULL,
	emailAddress VARCHAR(100) NOT NULL,
	telephone VARCHAR(20) NOT NULL,
	aboutUs VARCHAR(500) NOT NULL,
	positions INT(5),
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS vacancy_table (
	id INT(5) AUTO_INCREMENT,
	company VARCHAR(100) NOT NULL,
	salary INT(10),
	title VARCHAR(100) NOT NULL,
	description_1 VARCHAR(250) NOT NULL,
	description_2 VARCHAR(250),
	applicant VARCHAR(10),
	choice VARCHAR(5),
	open BOOL,
	awarded BOOL,
	ARDUINO BOOL,
	FPGA BOOL,
	ROBOTICS BOOL,
	WIFI BOOL,
	ANTENNAS BOOL,
	NETWORKING BOOL,
	PROCESSORDESIGN BOOL,
	IMAGEPROCESSING BOOL,
	PROGRAMMING BOOL,
	AUTOMATION BOOL,
	BIOMEDICAL BOOL,
	BIOMECHANICS BOOL,
	TELECOM BOOL,
	SEMICONDUCTORS BOOL,
	CIRCUITS BOOL,
	IOT BOOL,
	AI BOOL,
	SIGNALPROCESSING BOOL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS request_table (
	request_id INT(5) AUTO_INCREMENT,
	applicant VARCHAR(10) NOT NULL,
	currentApplicant VARCHAR(10) NOT NULL,
	vacancy INT(5) NOT NULL,
	vacancyName VARCHAR(100) NOT NULL,
	attended BOOL,
	gradedPoint DECIMAL(5, 4) NOT NULL,
	currentGradedPoint DECIMAL(5, 4) NOT NULL,
	PRIMARY KEY(request_id)
);